---
- name: Assert that ansible_pkg_mgr is defined
  ansible.builtin.assert:
    that:
      - ansible_pkg_mgr is defined
      - ansible_pkg_mgr != ""
      - ansible_pkg_mgr != "unknown"
    quiet: true

- ansible.builtin.include_tasks: "set-path-{{ ansible_pkg_mgr }}.yml"
