---
- name: Set ansible_pkg_mgr_prefix fact for Apple Silicon
  set_fact:
    ansible_pkg_mgr_prefix: "/opt/homebrew"
  when: ansible_architecture == "arm64"

- name: Set ansible_pkg_mgr_prefix fact for Intel macOS
  set_fact:
    ansible_pkg_mgr_prefix: "/usr/local"
  when: ansible_architecture == "x86_64"

- name: Set ansible_pkg_mgr_bin fact
  set_fact:
    ansible_pkg_mgr_bin: "{{ ansible_pkg_mgr_prefix }}/bin"

- name: Set ansible_pkg_mgr_path fact
  set_fact:
    ansible_pkg_mgr_path: "{{ ansible_pkg_mgr_bin }}:{{ ansible_env.PATH }}"
