---
- name: Converge
  hosts: all
  roles:
    - ableton.pkg_mgr_path
  tasks:
    - name: Write variables to file
      copy:
        content: |
          {{ ansible_pkg_mgr_bin }}
          {{ ansible_pkg_mgr_path }}
          {{ ansible_pkg_mgr_prefix }}
        dest: "/tmp/paths.txt"
